//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrepodsAndAnswers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int ID { get; set; }
        public int Question_ID { get; set; }
        public int Discipline_ID { get; set; }
        public string Correct { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
