//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrepodsAndAnswers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyEntities : DbContext
    {
        public StudyEntities()
            : base("name=StudyEntities")
        {
        }
        private static StudyEntities _context;
        public static StudyEntities GetContext() 
        {
            if(_context == null)
                _context = new StudyEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Dialogs> Dialogs { get; set; }
        public virtual DbSet<Disciplines> Disciplines { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Prepods> Prepods { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
    }
}
